---
title: "Data Wrangling"
author: "Alexander Thiel"
---


```{r}
library(vroom)
library(tidyverse)
library(data.table)

```

# Challenge Part 1:



```{r}

#importing data
patent_assignee_col_types <- list(
  patent_id = col_character(),
  assignee_id = col_character()
)

patent_assignee_tbl <- vroom(
  file       = "DataWrangling/Patent_data_reduced/patent_assignee.tsv", 
  delim      = "\t", 
  col_types  = patent_assignee_col_types,
  na         = c("", "NA", "NULL")
)

assignee_col_types <- list(
  id = col_character(),
  type = col_integer(),
  organization = col_character()
)

assignee_tbl <- vroom(
  file       = "DataWrangling/Patent_data_reduced/assignee.tsv", 
  delim      = "\t", 
  col_types  = assignee_col_types,
  na         = c("", "NA", "NULL")
)

patent_col_types <- list(
  id = col_character(),
  date = col_date("%Y-%m-%d"),
  num_claims = col_double()
)

patent_tbl <- vroom(
  file       = "DataWrangling/Patent_data_reduced/patent.tsv", 
  delim      = "\t", 
  col_types  = patent_col_types,
  na         = c("", "NA", "NULL")
)

uspc_col_types <- list(
  patent_id = col_character(),
  mainclass_id = col_character(),
  sequence = col_integer()
)

uspc_tbl <- vroom(
  file       = "DataWrangling/Patent_data_reduced/uspc.tsv", 
  delim      = "\t", 
  col_types  = uspc_col_types,
  na         = c("", "NA", "NULL")
)


rm(assignee_col_types,patent_col_types,uspc_col_types,patent_assignee_col_types)
```


```{r}
setDT(assignee_tbl)

setDT(patent_assignee_tbl)

setkey(assignee_tbl,id)
setkey(patent_assignee_tbl,assignee_id)


combined_data_tbl <- assignee_tbl[patent_assignee_tbl]

temp <-combined_data_tbl[,.N,by = organization]

setDT(temp)

setorder(temp,-N)

temp[1:5,,]

```

# Challenge Part 2:

```{r}
combined_data_tbl <- combined_data_tbl[patent_tbl, on = c(patent_id="id")]

combined_data_tbl <- na.omit(combined_data_tbl) #remove rows where organisation is NULL

temp_tbl <- combined_data_tbl[month(date)==5 & year(date)==2014 & !is.null(organization),.N, by = organization]

setorder(temp_tbl,-N)

temp_tbl[1:10,,]


```

# Challenge Part 3:
```{r}

setkey(uspc_tbl,NULL)
setkey(patent_tbl,NULL)
setkey(patent_assignee_tbl,NULL)
setDT(uspc_tbl)
combined_data_tbl <-uspc_tbl[patent_assignee_tbl,on = "patent_id"]
combined_data_tbl <- combined_data_tbl[assignee_tbl,on = c(assignee_id="id")]
setDT(combined_data_tbl)

combined_data_tbl <- na.omit(combined_data_tbl)

temp_tbl <-combined_data_tbl[,.(patents= .N),by=.(organization, mainclass_id)]  

setDT(temp_tbl)
setorder(temp_tbl,-patents)
temp_tbl<-temp_tbl[1:10,.('Occurence in top 10'=.N),by=mainclass_id] 
temp_tbl[1:5,,]   

```
